stages:
  train:
    cmd: python3 src/modeling/train.py
    deps:
    - data/external
    - data/raw/train.txt
    - src/modeling/train.py
    params:
    - train.embeddings
    - train.model
    - train.train_dataset
  evaluate:
    cmd: python3 -m src/modeling/evaluate.py
    deps:
    - src/modeling/evaluate.py
    metrics:
    - metrics/evaluation.json:
        cache: false
