prepare:
  train_size: 0.8
  test_size: 0.2
train:
  train_dataset: "data/raw/train.txt"
evaluate:
  test_dataset: "data/raw/test.txt"
predict:
  model: "sentiment_model_1_ep.h5"
  tokenizer: "tokenizer.pkl"
  embeddings: "data/external/glove.6B.100d.txt"

